# Generated by Django 6.0.2 on 2026-03-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Area', models.CharField(max_length=30)),
                ('VET', models.BooleanField(blank=True, default=None)),
                ('PDF_Title', models.CharField(blank=True, default=None, max_length=100)),
                ('PDF_File', models.FileField(upload_to='pdfs/')),
            ],
        ),
    ]
