# Generated by Django 6.0.2 on 2026-03-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='VET',
            field=models.CharField(max_length=10, null=1),
            preserve_default=1,
        ),
    ]
