# Generated by Django 6.0.2 on 2026-03-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_alter_teacher_pdf_title_alter_teacher_vet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='PDF_File',
            field=models.FileField(upload_to='media/pdfs/'),
        ),
    ]
