# Generated by Django 6.0.2 on 2026-04-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_alter_teacher_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='PDF_File',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
