# Generated by Django 6.0.5 on 2026-05-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_alter_teacher_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='task1',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='task1_weight',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='task2',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='task2_weight',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='task3',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='task3_weight',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='task4',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='task4_weight',
            field=models.CharField(blank=True),
        ),
    ]
