# Generated by Django 6.0.5 on 2026-05-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_teacher_task1_teacher_task1_weight_teacher_task2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='task1',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='task1_weight',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='task2',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='task2_weight',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='task3',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='task3_weight',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='task4',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='task4_weight',
            field=models.CharField(),
        ),
    ]
